server {
    listen 80;

    location = / {
        return 301 /personal_mission_statement/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /personal_mission_statement/index.html;
    }

    error_page 404 /personal_mission_statement/index.html;
}
